name: Terraform CI
on: push
env:
  ARM_CLIENT_ID: ${{ secrets.APP_ID }}
  ARM_CLIENT_SECRET: ${{  secrets.CLIENT_SECRET  }}
  ARM_SUBSCRIPTION_ID: ${{  secrets.SUBSCRIPTION_ID  }}
  ARM_TENANT_ID: ${{  secrets.TENANT_ID  }}
defaults:
  run:
    shell: bash
jobs:
  Terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ["audit", "shared-services", "dev", "prod"]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.26
    - name: Format check
      run: terraform fmt -check -diff -recursive
    - name: Initialize Terraform Directories
      run: |
        terraform init -input=false -upgrade=true ./environments/${{ matrix.environment }}
    - name: Validate Terraform syntax
      run: |
        terraform validate ./environments/${{ matrix.environment }}
    - name: Terraform Plan
      with:
        object_id: ${{  secrets.OBJECT_ID  }}
        app_id: ${{  secrets.APP_ID  }}
        client_secret: ${{  secrets.CLIENT_SECRET  }}
      run: |
        terraform plan -input=false -var 'client_secret="$client_secret"' -var 'app_id="$app_id"' -var 'object_id="$object_id"' -var-file=./environments/${{ matrix.environment }}/terraform.tfvars -out=./${{ matrix.environment }}tfplan ./environments/${{ matrix.environment }} 
    - name: Publish Plan Artifact
      uses: actions/upload-artifact@v2
      with:
        path: ./${{ matrix.environment }}tfplan