name: Terraform CI
on: push
env:
  ARM_CLIENT_ID: ${{ secrets.APP_ID }}
  ARM_CLIENT_SECRET: ${{  secrets.CLIENT_SECRET  }}
  ARM_SUBSCRIPTION_ID: ${{  secrets.SUBSCRIPTION_ID  }}
  ARM_TENANT_ID: ${{  secrets.TENANT_ID  }}
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.26
    - name: Format check
      run: terraform fmt -check -diff -recursive
    - name: Initialize Terraform Directories
      run: |
        terraform init -input=false -upgrade=true ./environments/audit
    - name: Validate Terraform syntax
      run: |
        terraform validate ./environments/audit
    - name: Terraform Plan
      run: |
        terraform plan -input=false -var-file=./environments/audit/terraform.tfvars -out=./audit.tfplan ./environments/audit 
    - name: Publish Plan Artifact
      uses: actions/upload-artifact@v2
      with:
        path: ./*.tfplan