name: 'Terraform'
description: 'Terraform CI'
on:
  push:
    branches: [ features ]
  pull_request:
    branches: [ master ]
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{  secrets.ACCESS_KEY  }}
    - ${{  secrets.APP_ID  }}
    - ${{  secrets.CLIENT_SECRET  }}
    - ${{  secrets.OBJECT_ID  }}
    - ${{  secrets.SUBSCRIPTION_ID  }}
    - ${{  secrets.TENANT_ID  }}
jobs:
  terraform_validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
